<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64;x86</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".gitignore" />
		<None Remove="ImGui\build\net40\ImGui.NET.targets" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
		<PackageReference Include="SharpDX.Desktop" Version="4.2.0">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="SharpDX.Direct3D12" Version="4.2.0" />
		<PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
		<PackageReference Include="SharpDX.RawInput" Version="4.2.0">
		  <NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
	</ItemGroup>
	
	
	<ItemGroup>
		<Content Include=".res\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	
	<ItemGroup>
	  <Compile Remove="ArcticFoxEngine Documentation\**" />
	  <EmbeddedResource Remove="ArcticFoxEngine Documentation\**" />
	  <None Remove="ArcticFoxEngine Documentation\**" />
	</ItemGroup>


	<!--ItemGroup>
	  <Content Include="..\ImGui.NET-1.89.7.1\deps\cimgui\win-x64\cimgui.dll" Link="ImGui\cimgui.dll">
		<PackagePath>runtimes/win-x64/native</PackagePath>
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		<Pack>true</Pack>
	  </Content>
	  <Content Include="ImGui\build\net40\ImGui.NET.targets">
		<PackagePath>build/net40/ImGui.NET.targets</PackagePath>
		<Pack>true</Pack>
	  </Content>
	</ItemGroup-->

	<ItemGroup>

		<Content Include="cimgui\win-x64\cimgui.dll" Condition=" '$(Platform)' == 'x64' ">
			<PackagePath>runtimes/win-x64/native</PackagePath>
			<Pack>true</Pack>
			<Link>cimgui.dll</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="cimgui\win-x86\cimgui.dll" Condition=" '$(Platform)' == 'x86' ">
			<PackagePath>runtimes/win-x86/native</PackagePath>
			<Pack>true</Pack>
			<Link>cimgui.dll</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="cimgui\win-arm64\cimgui.dll" Condition=" '$(Platform)' == 'ARM64' ">
			<PackagePath>runtimes/win-arm64/native</PackagePath>
			<Pack>true</Pack>
			<Link>cimgui.dll</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

	</ItemGroup>
	
	<ItemGroup>
	  <None Include=".res\icon.ico" />
	  <None Include=".res\Shaders\Mandelbrot\MandelbrotPixelShader.hlsl" />
	  <None Include=".res\Shaders\Unlit\PixelShader.hlsl" />
	  <None Include=".res\Shaders\Common.hlsl" />
	</ItemGroup>
	
	
	<ItemGroup>
	  <ProjectReference Include="..\CoolClassLibrary\CoolClassLibrary.csproj" />
	</ItemGroup>


</Project>