<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Remove=".gitignore" />
		<None Remove=".res\shaders.hlsl" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ImGui.NET" Version="1.89.7.1" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
		<PackageReference Include="SharpDX.Desktop" Version="4.2.0">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="SharpDX.Direct3D12" Version="4.2.0" />
		<PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
		<PackageReference Include="SharpDX.RawInput" Version="4.2.0">
		  <NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
		<PackageReference Include="Veldrid.ImGui" Version="5.72.0" />
		<PackageReference Include="Vortice.D3DCompiler" Version="2.2.0" />
		<PackageReference Include="Vortice.Direct3D11" Version="2.2.0" />
		<PackageReference Include="Vortice.Mathematics" Version="1.6.2" />
	</ItemGroup>
	
	
	<ItemGroup>
		<Content Include=".res\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	
	<ItemGroup>
	  <Content Include=".Documentation\GraphicsResources.txt" />
	  <Content Include=".Documentation\Input.txt" />
	</ItemGroup>
	
	
	<ItemGroup>
	  <None Include=".Documentation\EventLoop.txt" />
	  <None Include=".Documentation\Setup.txt" />
	  <None Include=".Documentation\Terms.txt" />
	  <None Include=".res\icon.ico" />
	  <None Include=".res\mandelbrot_shader.hlsl" />
	</ItemGroup>
	
	
	<ItemGroup>
	  <ProjectReference Include="..\CoolClassLibrary\CoolClassLibrary.csproj" />
	</ItemGroup>


</Project>